### ISSUE TITLE
Process does not exit when all app windows are closed

### ISSUE THREAD

**Issue by c12i** [holochain/hc-spin#1]
At the moment exiting the program vis `Ctrl C` closes the open windows, the opposite does not apply, the program continues to run despite all windows closed, is this behaviour expected?

Log output when all windows are closed

```shell
[1] [hc-spin] | [hc sandbox]: 
[1] npm run launch:happ exited with code 0
```

**Comment by matthme** [comment]
Thank you, that's not intended. I guess I just never tested that during development, will look how I can fix it.

**Comment by matthme** [comment]
Okay, there was an issue with the hc sandbox processes not getting properly cleaned up.
But I think the main issue here is that `hc-spin` is not the only process that's running as part of the `npm start` command and I can only exit the `hc-spin` process on closing of the windows but not the `holochain-playground` process or the process of the running UI dev server.
So I think there is nothing I can do to not require the developer to also press Ctrl+C to quit those other processes.

**Comment by c12i** [comment]
> hc-spin is not the only process that's running as part of the npm start command and I can only exit the hc-spin process on closing of the windows but not the holochain-playground process or the process of the running UI dev serve

Ah, I see, it seems that developers may need to handle the termination of these additional processes manually on their end then, a decent compromise
