### ISSUE TITLE
Check for existing electron binary on PATH

### ISSUE THREAD

**Issue by matthme** [holochain/hc-spin#8]
To support running hc-spin in nixOS, electron may be shipped with holonix. To support this use case seamlessly, hc-spin should
1. Check if an electron binary has been provided via the `ELECTRON_BINARY` env var, if yes use this one
2. Check if an electron binary is on PATH and if the version matches the expected version use this binary, otherwise log a warning and continue with step 3
3. Search the electron binary in the node_modules folder and use this one

**Comment by matthme** [comment]
@steveej

**Comment by steveej** [comment]
@matthme i agree with the logic.

how about a version check on an external binary to compare it with the requirement in the package.json, and print a warning if the major version isn't a match?
